server:
  servlet:
    context-path: /lego-manager
spring:
  datasource:
    username: shark
    password: NeshWood
    driver-class-name: org.postgresql.Driver
  jackson:
    default-property-inclusion: non_null
  jpa:
    mapping-resources:
      - mappings/categories.xml
      - mappings/colors.xml
      - mappings/partColors.xml
      - mappings/parts.xml
      - mappings/series.xml
      - mappings/setParts.xml
      - mappings/sets.xml
      - mappings/users.xml
      - mappings/userSets.xml
      - mappings/userParts.xml
      - mappings/loader.xml
    show-sql: true