server:
  servlet:
    context-path: /lego-manager
spring:
  datasource:
    username: shark
    password: NeshWood
    driver-class-name: org.postgresql.Driver
  jackson:
    default-property-inclusion: non_null