-- Таблица серий наборов
CREATE SEQUENCE LEGO_SERIES_SEQ;
CREATE TABLE LEGO_SERIES
(
    LEGO_ID   BIGINT                 NOT NULL,
    LEGO_NAME CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT PK_SERIES PRIMARY KEY (LEGO_ID)
);
ALTER TABLE LEGO_SERIES
    ADD CONSTRAINT UK_SERIES UNIQUE (LEGO_NAME);

-- Таблица наборов
CREATE SEQUENCE LEGO_SET_SEQ;
CREATE TABLE LEGO_SET
(
    LEGO_ID        BIGINT                 NOT NULL,
    LEGO_NAME      CHARACTER VARYING(255) NOT NULL,
    LEGO_NUMBER    CHARACTER VARYING(10)  NOT NULL,
    LEGO_YEAR      INTEGER                NOT NULL,
    LEGO_SERIES_ID BIGINT                 NOT NULL,
    CONSTRAINT PK_SET PRIMARY KEY (LEGO_ID),
    CONSTRAINT FK_SET_SERIES FOREIGN KEY (LEGO_SERIES_ID) REFERENCES LEGO_SERIES (LEGO_ID)
);
ALTER TABLE LEGO_SET
    ADD CONSTRAINT UK_SET UNIQUE (LEGO_NUMBER);
CREATE INDEX IDX_SET_SERIES ON LEGO_SET (LEGO_SERIES_ID);

-- Таблица цветов
CREATE SEQUENCE LEGO_COLOR_SEQ;
CREATE TABLE LEGO_COLOR
(
    LEGO_ID        BIGINT                 NOT NULL,
    LEGO_NAME      CHARACTER VARYING(255) NOT NULL,
    LEGO_HEX_COLOR CHARACTER VARYING(6)   NOT NULL,
    CONSTRAINT PK_COLOR PRIMARY KEY (LEGO_ID)
);
ALTER TABLE LEGO_COLOR
    ADD CONSTRAINT UK_COLOR UNIQUE (LEGO_NAME);

-- Таблица категорий деталей
CREATE SEQUENCE LEGO_PART_CATEGORY_SEQ;
CREATE TABLE LEGO_PART_CATEGORY
(
    LEGO_ID   BIGINT                 NOT NULL,
    LEGO_NAME CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT PK_PART_CATEGORY PRIMARY KEY (LEGO_ID)
);
ALTER TABLE LEGO_PART_CATEGORY
    ADD CONSTRAINT UK_PART_CATEGORY UNIQUE (LEGO_NAME);

-- Таблица деталей
CREATE SEQUENCE LEGO_PART_SEQ;
CREATE TABLE LEGO_PART
(
    LEGO_ID               BIGINT                 NOT NULL,
    LEGO_NAME             CHARACTER VARYING(255) NOT NULL,
    LEGO_PART_CATEGORY_ID BIGINT                 NOT NULL,
    CONSTRAINT PK_PART PRIMARY KEY (LEGO_ID),
    CONSTRAINT FK_PART_PART_CATEGORY FOREIGN KEY (LEGO_PART_CATEGORY_ID) REFERENCES LEGO_PART_CATEGORY (LEGO_ID)
);
ALTER TABLE LEGO_PART
    ADD CONSTRAINT UK_PART UNIQUE (LEGO_NAME);
CREATE INDEX IDX_PART_PART_CATEGORY ON LEGO_PART (LEGO_PART_CATEGORY_ID);

-- Таблица номеров деталей
CREATE SEQUENCE LEGO_PART_NUMBER_SEQ;
CREATE TABLE LEGO_PART_NUMBER
(
    LEGO_ID      BIGINT                 NOT NULL,
    LEGO_PART_ID BIGINT                 NOT NULL,
    LEGO_NUMBER  CHARACTER VARYING(255) NOT NULL,
    LEGO_MAIN    BOOLEAN                NOT NULL DEFAULT FALSE,
    CONSTRAINT PK_PART_NUMBER PRIMARY KEY (LEGO_ID),
    constraint FK_PART_NUMBER_PART FOREIGN KEY (LEGO_PART_ID) REFERENCES LEGO_PART (LEGO_ID)
);
ALTER TABLE LEGO_PART_NUMBER
    ADD CONSTRAINT UK_PART_NUMBER UNIQUE (LEGO_PART_ID, LEGO_NUMBER);
CREATE INDEX IDX_LEGO_PART_NUMBER_PART ON LEGO_PART_NUMBER (LEGO_PART_ID);

-- Таблица цветов деталей
CREATE SEQUENCE LEGO_PART_COLOR_SEQ;
CREATE TABLE LEGO_PART_COLOR
(
    LEGO_ID       BIGINT NOT NULL,
    LEGO_PART_ID  BIGINT NOT NULL,
    LEGO_COLOR_ID BIGINT NOT NULL,
    CONSTRAINT PK_PART_COLOR PRIMARY KEY (LEGO_ID),
    CONSTRAINT FK_PART_COLOR_PART FOREIGN KEY (LEGO_PART_ID) REFERENCES LEGO_PART (LEGO_ID),
    CONSTRAINT FK_PART_COLOR_COLOR FOREIGN KEY (LEGO_COLOR_ID) REFERENCES LEGO_COLOR (LEGO_ID)
);
ALTER TABLE LEGO_PART_COLOR
    ADD CONSTRAINT UK_PART_COLOR UNIQUE (LEGO_PART_ID, LEGO_COLOR_ID);
CREATE INDEX IDX_PART_COLOR_PART ON LEGO_PART_COLOR (LEGO_PART_ID);
CREATE INDEX IDX_PART_COLOR_COLOR ON LEGO_PART_COLOR (LEGO_COLOR_ID);

-- таблица номеров цветов деталей
CREATE SEQUENCE LEGO_PART_COLOR_NUMBER_SEQ;
CREATE TABLE LEGO_PART_COLOR_NUMBER
(
    LEGO_ID            BIGINT                 NOT NULL,
    LEGO_PART_COLOR_ID BIGINT                 NOT NULL,
    LEGO_NUMBER        CHARACTER VARYING(255) NOT NULL,
    LEGO_MAIN          BOOLEAN                NOT NULL DEFAULT FALSE,
    CONSTRAINT PK_PART_COLOR_NUMBER PRIMARY KEY (LEGO_ID),
    CONSTRAINT FK_PART_COLOR_NUMBER_PART_COLOR FOREIGN KEY (LEGO_PART_COLOR_ID) REFERENCES LEGO_PART_COLOR (LEGO_ID)
);
ALTER TABLE LEGO_PART_COLOR_NUMBER
    ADD CONSTRAINT UK_PART_color_NUMBER UNIQUE (LEGO_PART_COLOR_ID, LEGO_NUMBER);
CREATE INDEX IDX_LEGO_PART_COLOR_NUMBER_PART ON LEGO_PART_COLOR_NUMBER (LEGO_PART_COLOR_ID);

-- Таблица деталей наборов
CREATE SEQUENCE LEGO_SET_PART_SEQ;
CREATE TABLE LEGO_SET_PART
(
    LEGO_ID            BIGINT  NOT NULL,
    LEGO_SET_ID        BIGINT  NOT NULL,
    LEGO_PART_COLOR_ID BIGINT  NOT NULL,
    LEGO_COUNT         INTEGER NOT NULL,
    CONSTRAINT PK_SET_PART PRIMARY KEY (LEGO_ID),
    CONSTRAINT FK_SET_PART_SET FOREIGN KEY (LEGO_SET_ID) REFERENCES LEGO_SET (LEGO_ID),
    CONSTRAINT FK_SET_PART_PART_COLOR FOREIGN KEY (LEGO_PART_COLOR_ID) REFERENCES LEGO_PART_COLOR (LEGO_ID)
);
ALTER TABLE LEGO_SET_PART
    ADD CONSTRAINT UK_SET_PART UNIQUE (LEGO_SET_ID, LEGO_PART_COLOR_ID);
CREATE INDEX IDX_SET_PART_SET ON LEGO_SET_PART (LEGO_SET_ID);
CREATE INDEX IDX_SET_PART_PART_COLOR ON LEGO_SET_PART (LEGO_PART_COLOR_ID);

-- Таблица владельцев
CREATE SEQUENCE LEGO_USERS_SEQ;
CREATE TABLE LEGO_USERS
(
    LEGO_ID   BIGINT                 NOT NULL,
    LEGO_NAME CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT PK_USERS PRIMARY KEY (LEGO_ID)
);
ALTER TABLE LEGO_USERS
    ADD CONSTRAINT UK_USERS UNIQUE (LEGO_NAME);

-- Таблица наборов владельца
CREATE SEQUENCE LEGO_USER_SETS_SEQ;
CREATE TABLE LEGO_USER_SETS
(
    LEGO_ID      BIGINT  NOT NULL,
    LEGO_USER_ID BIGINT  NOT NULL,
    LEGO_SET_ID  BIGINT  NOT NULL,
    LEGO_COUNT   INTEGER NOT NULL,
    CONSTRAINT PK_USER_SETS PRIMARY KEY (LEGO_ID),
    CONSTRAINT FK_USER_SET_USER FOREIGN KEY (LEGO_USER_ID) REFERENCES LEGO_USERS (LEGO_ID),
    CONSTRAINT FK_USER_SET_SET FOREIGN KEY (LEGO_SET_ID) REFERENCES LEGO_SET (LEGO_ID)
);
ALTER TABLE LEGO_USER_SETS
    ADD CONSTRAINT UK_USER_SET UNIQUE (LEGO_USER_ID, LEGO_SET_ID);
CREATE INDEX IDX_USER_SET_USER ON LEGO_USER_SETS (LEGO_USER_ID);
CREATE INDEX IDX_USER_SET_SET ON LEGO_USER_SETS (LEGO_SET_ID);

-- Таблица деталей владельца
CREATE SEQUENCE LEGO_USER_PART_SEQ;
CREATE TABLE LEGO_USER_PARTS
(
    LEGO_ID            BIGINT  NOT NULL,
    LEGO_USER_ID       BIGINT  NOT NULL,
    LEGO_PART_COLOR_ID BIGINT  NOT NULL,
    LEGO_COUNT         INTEGER NOT NULL,
    CONSTRAINT PK_USER_PARTS PRIMARY KEY (LEGO_ID),
    CONSTRAINT FK_USER_PART_COLOR_USER FOREIGN KEY (LEGO_USER_ID) REFERENCES LEGO_USERS (LEGO_ID),
    CONSTRAINT FK_USER_PART_COLOR_PART_COLOR FOREIGN KEY (LEGO_PART_COLOR_ID) REFERENCES LEGO_PART_COLOR (LEGO_ID)
);
ALTER TABLE LEGO_USER_PARTS
    ADD CONSTRAINT UK_USER_PART UNIQUE (LEGO_USER_ID, LEGO_PART_COLOR_ID);
CREATE INDEX IDX_USER_PART_COLOR_USER ON LEGO_USER_PARTS (LEGO_USER_ID);
CREATE INDEX IDX_USER_PART_COLOR_PART_COLOR ON LEGO_USER_PARTS (LEGO_PART_COLOR_ID);

CREATE
ALIAS STRING_TO_ARRAY FOR "ru.shark.home.legomanager.util.H2Functions.stringToArray";
CREATE
ALIAS ARRAY_POSITION FOR "ru.shark.home.legomanager.util.H2Functions.arrayPosition";

CREATE TEMPORARY TABLE LEGO_PART_LOAD_TABLE
(
    LEGO_ID             BIGINT NOT NULL,
    LEGO_COUNT          INTEGER NOT NULL,
    LEGO_NAME           CHARACTER VARYING(255) NOT NULL,
    LEGO_URL            CHARACTER VARYING(255)
);

CREATE TEMPORARY TABLE LEGO_PART_LOAD_NUMBER_TABLE
(
    LEGO_PART_ID        BIGINT NOT NULL,
    LEGO_NUMBER         CHARACTER VARYING(255) NOT NULL,
    LEGO_TYPE           CHARACTER VARYING(255) NOT NULL
);