-- Таблица оружия
CREATE SEQUENCE LEGO_SERIES_SEQ;
CREATE TABLE LEGO_SERIES (
    LEGO_ID BIGINT NOT NULL,
    LEGO_NAME CHARACTER VARYING (255) NOT NULL,
    CONSTRAINT PK_SERIES PRIMARY KEY(LEGO_ID)
);
ALTER TABLE LEGO_SERIES ADD CONSTRAINT UK_SERIES UNIQUE(LEGO_NAME);