-- Таблица серий наборов
CREATE SEQUENCE LEGO_SERIES_SEQ;
CREATE TABLE LEGO_SERIES
(
    LEGO_ID   BIGINT                 NOT NULL,
    LEGO_NAME CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT PK_SERIES PRIMARY KEY (LEGO_ID)
);
ALTER TABLE LEGO_SERIES
    ADD CONSTRAINT UK_SERIES UNIQUE (LEGO_NAME);

-- Таблица наборов
CREATE SEQUENCE LEGO_SET_SEQ;
CREATE TABLE LEGO_SET
(
    LEGO_ID        BIGINT                 NOT NULL,
    LEGO_NAME      CHARACTER VARYING(255) NOT NULL,
    LEGO_NUMBER    CHARACTER VARYING(10)  NOT NULL,
    LEGO_YEAR      INTEGER                NOT NULL,
    LEGO_SERIES_ID BIGINT                 NOT NULL,
    CONSTRAINT PK_SET PRIMARY KEY (LEGO_ID),
    CONSTRAINT FK_SET_SERIES FOREIGN KEY (LEGO_SERIES_ID) REFERENCES LEGO_SERIES (LEGO_ID)
);
ALTER TABLE LEGO_SET
    ADD CONSTRAINT UK_SET UNIQUE (LEGO_NUMBER);
CREATE INDEX IDX_SET_SERIES ON LEGO_SET (LEGO_SERIES_ID);

-- Таблица цветов
CREATE SEQUENCE LEGO_COLOR_SEQ;
CREATE TABLE LEGO_COLOR
(
    LEGO_ID        BIGINT                 NOT NULL,
    LEGO_NAME      CHARACTER VARYING(255) NOT NULL,
    LEGO_HEX_COLOR CHARACTER VARYING(6)   NOT NULL,
    CONSTRAINT PK_COLOR PRIMARY KEY (LEGO_ID)
);
ALTER TABLE LEGO_COLOR
    ADD CONSTRAINT UK_COLOR UNIQUE (LEGO_NAME);

-- Таблица категорий деталей
CREATE SEQUENCE LEGO_PART_CATEGORY_SEQ;
CREATE TABLE LEGO_PART_CATEGORY
(
    LEGO_ID   BIGINT                 NOT NULL,
    LEGO_NAME CHARACTER VARYING(255) NOT NULL,
    CONSTRAINT PK_PART_CATEGORY PRIMARY KEY (LEGO_ID)
);
ALTER TABLE LEGO_PART_CATEGORY
    ADD CONSTRAINT UK_PART_CATEGORY UNIQUE (LEGO_NAME);

-- Таблица деталей
CREATE SEQUENCE LEGO_PART_SEQ;
CREATE TABLE LEGO_PART
(
    LEGO_ID               BIGINT                 NOT NULL,
    LEGO_NAME             CHARACTER VARYING(255) NOT NULL,
    LEGO_NUMBER           CHARACTER VARYING(10)  NOT NULL,
    LEGO_PART_CATEGORY_ID BIGINT                 NOT NULL,
    CONSTRAINT PK_PART PRIMARY KEY (LEGO_ID),
    CONSTRAINT FK_PART_PART_CATEGORY FOREIGN KEY (LEGO_PART_CATEGORY_ID) REFERENCES LEGO_PART_CATEGORY (LEGO_ID)
);
ALTER TABLE LEGO_PART
    ADD CONSTRAINT UK_PART UNIQUE (LEGO_NAME);
CREATE INDEX IDX_PART_PART_CATEGORY ON LEGO_PART (LEGO_PART_CATEGORY_ID);

-- Таблица цветов деталей
CREATE SEQUENCE LEGO_PART_COLOR_SEQ;
CREATE TABLE LEGO_PART_COLOR
(
    LEGO_ID       BIGINT                NOT NULL,
    LEGO_PART_ID  BIGINT                NOT NULL,
    LEGO_COLOR_ID BIGINT                NOT NULL,
    LEGO_NUMBER   CHARACTER VARYING(10) NOT NULL,
    CONSTRAINT PK_PART_COLOR PRIMARY KEY (LEGO_ID),
    CONSTRAINT FK_PART_COLOR_PART FOREIGN KEY (LEGO_PART_ID) REFERENCES LEGO_PART (LEGO_ID),
    CONSTRAINT FK_PART_COLOR_COLOR FOREIGN KEY (LEGO_COLOR_ID) REFERENCES LEGO_COLOR (LEGO_ID)
);
ALTER TABLE LEGO_PART_COLOR
    ADD CONSTRAINT UK_PART_COLOR_NUMBER UNIQUE (LEGO_NUMBER);
ALTER TABLE LEGO_PART_COLOR
    ADD CONSTRAINT UK_PART_COLOR UNIQUE (LEGO_PART_ID, LEGO_COLOR_ID);
CREATE INDEX IDX_PART_COLOR_PART ON LEGO_PART_COLOR (LEGO_PART_ID);
CREATE INDEX IDX_PART_COLOR_COLOR ON LEGO_PART_COLOR (LEGO_COLOR_ID);